other
colorPalette
	"Answer anArray with a list of color to be used by the receiver"

	"^#('aliceblue' 'beige' 'brown' 'burlywood' 'cadetblue' 'chocolate' 'coral' 'cornsilk' 'crimson' 'darkcyan' 'darkgoldenrod' 'darkgray' 'darkgreen' 'darkkhaki' 'darkolivegreen'  
'darkred' 'darkslateblue' 'darkslategray' 'firebrick' 'gold' 'goldenrod' 'gray' 'lightblue' 'indigo' 'ivory' 'khaki' 'lavender' 'lightcyan' 'lightgoldenrodyellow' 'lightgray' 'olive' 'peru' 'red' 
'saddlebrown' 'steelblue' 'tan') "


^#('#000063' '#000078' '#003366' '#003366' '#003366' '#0033CC' '#0099FF' '#097054' '#1F1209' '#330033' '#5A79A5' '#606060' '#6194BC' '#6599FF' '#660033' '#669900' '#777B88' 
'#834C24' '#990033' '#993300' '#99CC99' '#99CC99' '#99CCFF' '#9CAAC6' '#A5D1F3' '#B3B3D7' '#CCCC99' '#CCCCCC' '#CE0000' '#D0EAFF' '#D1CAB0' '#DEE7EF' '#E0E6FF' '#E4001B' 
'#ECECEC' '#FF9900' '#FFCC00' '#FFDE00' '#FFF8DC' '#FFFFFF')