other
colorPalette
	"Answer anArray with a list of color to be used by the receiver"

	^#('aliceblue' 'beige' 'brown' 'burlywood' 'cadetblue' 'chocolate' 'coral' 'cornsilk' 'crimson' 'darkcyan' 'darkgoldenrod' 'darkgray' 'darkgreen' 'darkkhaki' 'darkolivegreen'  'darkred' 'darkslateblue' 'darkslategray' 'firebrick' 'gold' 'goldenrod' 'gray' 'lightblue' 'indigo' 'ivory' 'khaki' 'lavender' 'lightcyan' 'lightgoldenrodyellow' 'lightgray' 'olive' 'peru' 'red' 'saddlebrown' 'steelblue' 'tan')